package message;

public enum CommandType {
    AUTH_REQUEST,
    AUTH_RESPONSE,
    FILE_MESSAGE_HEADER,
    FILE_MESSAGE_PART,
    RESULT_OF_SYNCH_FILE,
    LIST_FILE_REQUEST,
    LIST_FILE_RESPONSE
}
